Update README.md
nkmishra1997/github_example pull request #7
Opened 2017-06-04 17:01 UTC by umangahuja1

2017-06-04 17:06 UTC, Manmeet-123 commented
resolve this conflict

2017-06-04 19:17 UTC, umangahuja1 commented
New Update

2017-06-05 07:48 UTC, nkmishra1997 commented
what have to tried to do?

2017-06-05 07:49 UTC, nkmishra1997 requested changes
see those >>>>> HEAD... these should not be pushed to the repository.... they are indicators that this is a merge conflict

2017-06-08 00:33 UTC, closed without merging